/**
 * "What to expect" for every track whose examples are bytes (PLAN.md §4.2, §5.2).
 *
 * Each tester generates its examples at catalog time and writes them into `catalog.json`
 * in snake_case, exactly as its Rust structs are named. Kafka's look like this:
 *
 * ```jsonc
 * {
 *   "title": "ApiVersions v4",
 *   "request": "ApiVersions v4, client_id \"kafka-cli\"",
 *   "request_hex": "00 00 00 23 …",
 *   "request_fields": [{ "offset": 0, "length": 4, "field": "size", "value": "35" }],
 *   "response": "error_code 0, 3 api keys",
 *   "response_hex": "…",
 *   "note": "the response header for ApiVersions is v0 — no tagged fields"
 * }
 * ```
 *
 * and a wasm or link example looks like the same thing with different names:
 *
 * ```jsonc
 * {
 *   "title": "add(2, 3)",
 *   "module": "8 sections, one exported function",
 *   "module_hex": "00 61 73 6d 01 00 00 00 …",
 *   "module_fields": [ … ],
 *   "invoke": "run --invoke add add.wasm 2 3",
 *   "stdout": "5",
 *   "exit_code": 0
 * }
 * ```
 *
 * The reader is deliberately generic: **any** `<name>_hex` key becomes a labelled block of
 * bytes, with `<name>` as its summary and `<name>_fields` as its annotations — so a tester
 * can name its blocks after the thing it is showing and the site needs no new component.
 * It is equally forgiving, because these are generated by crates that are still moving: a
 * missing array means "no examples", an unknown key is ignored, an empty hex string means
 * the block is prose rather than a frame, and a field whose range falls outside the bytes
 * is clamped or dropped instead of breaking the page.
 */
import type {
	ByteExample,
	ExampleBlock,
	ExampleEnv,
	ExampleField,
	ExampleFixture,
	ExampleKindTag,
	StageSpec,
	TrackId,
	TranscriptLine
} from '../types';

const HEX_RE = /^[0-9a-fA-F]{2}$/;

/** Accepts `"00 01 02"`, `"000102"`, `"0x00,0x01"` and newline-separated dumps. */
export function readHex(input: unknown): Uint8Array | null {
	if (input instanceof Uint8Array) return input;
	if (Array.isArray(input)) {
		const out = input.map((n) => Number(n)).filter((n) => Number.isInteger(n) && n >= 0 && n <= 255);
		return out.length === input.length ? Uint8Array.from(out) : null;
	}
	if (typeof input !== 'string') return null;
	const cleaned = input.replace(/0x/gi, '').replace(/[\s,:_|]+/g, '');
	if (cleaned.length === 0) return null;
	if (cleaned.length % 2 !== 0) return null;
	const out = new Uint8Array(cleaned.length / 2);
	for (let i = 0; i < out.length; i++) {
		const pair = cleaned.slice(i * 2, i * 2 + 2);
		if (!HEX_RE.test(pair)) return null;
		out[i] = parseInt(pair, 16);
	}
	return out;
}

function text(value: unknown): string {
	if (typeof value === 'string') return value;
	if (typeof value === 'number' || typeof value === 'boolean') return String(value);
	return '';
}

function normalizeFields(raw: unknown, byteLength: number): ExampleField[] {
	if (!Array.isArray(raw)) return [];
	const out: ExampleField[] = [];
	for (const entry of raw) {
		if (!entry || typeof entry !== 'object') continue;
		const o = entry as Record<string, unknown>;
		const offset = Number(o.offset ?? o.start ?? NaN);
		const rawLength = Number(o.length ?? o.len ?? NaN);
		const name = text(o.field ?? o.name);
		if (!name) continue;
		if (!Number.isFinite(offset) || offset < 0) continue;
		const length = Number.isFinite(rawLength) && rawLength > 0 ? Math.floor(rawLength) : 0;
		// A frame that lost bytes in transit must not paint highlights past its end.
		const start = Math.min(Math.floor(offset), byteLength);
		const end = Math.min(start + length, byteLength);
		const field: ExampleField = {
			offset: start,
			length: Math.max(0, end - start),
			name,
			value: text(o.value)
		};
		if (o.varies === true) field.varies = true;
		out.push(field);
	}
	return out.sort((a, b) => a.offset - b.offset || a.length - b.length);
}

const KINDS: ExampleKindTag[] = ['wire', 'text', 'closed', 'silence'];

function normalizeKind(raw: unknown, hasAnyBytes: boolean): ExampleKindTag {
	if (typeof raw === 'string' && (KINDS as string[]).includes(raw)) return raw as ExampleKindTag;
	// No `kind` at all (an older catalog): infer it from whether there are bytes to show.
	if (raw === undefined || raw === null || raw === '') return hasAnyBytes ? 'wire' : 'text';
	return 'other';
}

/**
 * The fixture state the example was captured against. Shaped as
 * `{ topics: { alias: { name, id, partitions } }, group }`, and every part is optional.
 */
function normalizeEnv(raw: unknown): ExampleEnv | null {
	if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
	const o = raw as Record<string, unknown>;
	const topics: ExampleFixture[] = [];
	if (o.topics && typeof o.topics === 'object' && !Array.isArray(o.topics)) {
		for (const [key, value] of Object.entries(o.topics as Record<string, unknown>)) {
			if (!value || typeof value !== 'object') continue;
			const t = value as Record<string, unknown>;
			const name = text(t.name);
			if (!name) continue;
			const partitions = Number(t.partitions);
			topics.push({
				key,
				name,
				id: text(t.id) || null,
				partitions: Number.isFinite(partitions) && partitions > 0 ? partitions : null
			});
		}
	}
	const group = text(o.group) || null;
	if (topics.length === 0 && group === null) return null;
	return { topics, group };
}

/** `client_hello` → `client hello`; `request`/`response` keep their direction arrows. */
export function labelForBlock(key: string): string {
	if (key === 'request') return 'request →';
	if (key === 'response') return '← response';
	return key.replace(/[_-]+/g, ' ').trim();
}

function block(key: string, label: unknown, summary: unknown, hex: unknown, fields: unknown): ExampleBlock {
	const bytes = readHex(hex);
	return {
		key,
		label: text(label) || labelForBlock(key),
		summary: text(summary),
		bytes,
		fields: normalizeFields(fields, bytes?.length ?? 0)
	};
}

/** `requestHex` → `request_hex`, so a camelCase generator reads the same as a snake_case one. */
function snake(key: string): string {
	return key.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/**
 * Every block in the example, in the order the generator wrote them, with `request` and
 * `response` pinned to the front when they are there (a reader expects the request first,
 * whatever order the JSON happened to use).
 */
function normalizeBlocks(o: Record<string, unknown>): ExampleBlock[] {
	const out: ExampleBlock[] = [];
	const seen = new Set<string>();

	// An explicit `blocks` array wins: it can name and order them however it likes.
	if (Array.isArray(o.blocks)) {
		for (const entry of o.blocks) {
			if (!entry || typeof entry !== 'object') continue;
			const b = entry as Record<string, unknown>;
			const key = snake(text(b.key ?? b.name ?? b.id) || `block${out.length + 1}`);
			if (seen.has(key)) continue;
			seen.add(key);
			out.push(block(key, b.label ?? b.title, b.summary ?? b.text, b.hex ?? b.bytes, b.fields));
		}
	}

	// Otherwise (and additionally) every `<name>_hex` key is a block of its own.
	for (const [rawKey, value] of Object.entries(o)) {
		const key = snake(rawKey);
		if (!key.endsWith('_hex')) continue;
		const name = key.slice(0, -4);
		if (!name || seen.has(name)) continue;
		seen.add(name);
		out.push(block(name, o[`${name}_label`], o[name], value, o[`${name}_fields`] ?? o[`${name}Fields`]));
	}

	const rank = (b: ExampleBlock) => (b.key === 'request' ? 0 : b.key === 'response' ? 1 : 2);
	return out.sort((a, b) => rank(a) - rank(b));
}

const LINE_KINDS: TranscriptLine['kind'][] = ['input', 'key', 'stdout', 'stderr', 'terminal', 'exit', 'note'];

function pushLines(out: TranscriptLine[], kind: TranscriptLine['kind'], value: unknown) {
	const body = text(value);
	if (body === '') return;
	for (const line of body.split('\n')) out.push({ kind, text: line });
}

/**
 * What running it printed. Either an explicit `transcript` array (strings, or
 * `{ kind, text }` rows), or the plain `command`/`stdout`/`stderr`/`exit_code` keys a
 * tester is most likely to emit for "and this is what it should print".
 */
function normalizeTranscript(o: Record<string, unknown>): TranscriptLine[] {
	const out: TranscriptLine[] = [];
	if (Array.isArray(o.transcript)) {
		for (const entry of o.transcript) {
			if (typeof entry === 'string') {
				pushLines(out, 'stdout', entry);
				continue;
			}
			if (!entry || typeof entry !== 'object') continue;
			const row = entry as Record<string, unknown>;
			const kind = text(row.kind ?? row.stream);
			pushLines(
				out,
				(LINE_KINDS as string[]).includes(kind) ? (kind as TranscriptLine['kind']) : 'stdout',
				row.text ?? row.line ?? row.value
			);
		}
		return out;
	}
	pushLines(out, 'input', o.command ?? o.invoke ?? o.argv ?? o.run);
	pushLines(out, 'stdout', o.stdout);
	pushLines(out, 'stderr', o.stderr);
	const status = o.exit_code ?? o.exitCode ?? o.status;
	if (typeof status === 'number') out.push({ kind: 'exit', text: String(status) });
	return out;
}

/** One catalog example → the shape the renderer wants, or `null` when there is nothing in it. */
export function normalizeByteExample(raw: unknown, index = 0): ByteExample | null {
	if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
	const o = raw as Record<string, unknown>;
	const blocks = normalizeBlocks(o);
	const transcript = normalizeTranscript(o);
	const anyBytes = blocks.some((b) => (b.bytes?.length ?? 0) > 0);
	const anySummary = blocks.some((b) => b.summary !== '');
	if (!anyBytes && !anySummary && transcript.length === 0) return null;
	const note = text(o.note);
	return {
		title: text(o.title) || `Example ${index + 1}`,
		kind: normalizeKind(o.kind, anyBytes),
		note: note === '' ? null : note,
		env: normalizeEnv(o.env),
		blocks,
		transcript
	};
}

/** A list of raw catalog entries → the examples the renderer can draw. */
export function normalizeByteExamples(raw: unknown): ByteExample[] {
	if (!Array.isArray(raw)) return [];
	const out: ByteExample[] = [];
	raw.forEach((entry, i) => {
		const example = normalizeByteExample(entry, i);
		if (example) out.push(example);
	});
	return out;
}

/** One block by key, for a caller that knows the tester's names (`request`, `module`). */
export function blockOf(example: ByteExample, key: string): ExampleBlock | undefined {
	return example.blocks.find((b) => b.key === key);
}

/** `true` when a block carries bytes worth drawing a hex dump for. */
export function hasBytes(block: ExampleBlock | undefined | null): boolean {
	return Boolean(block && block.bytes && block.bytes.length > 0);
}

/**
 * The examples carried *inline* on a stage. The generated catalog does not carry them (see
 * `loadExamples`), so this is the path for fixtures and tests — and for a catalog served by
 * a newer `byo` that still inlines them.
 */
export function inlineExamples(stage: StageSpec | null | undefined): ByteExample[] {
	return normalizeByteExamples(stage?.examples);
}

/**
 * One stage's examples, fetched on demand.
 *
 * `npm run sync` writes a file per stage per track, and `import.meta.glob` turns each into
 * its own chunk — so opening one stage downloads that stage's frames and nothing else,
 * instead of every page paying for all of them. A stage with no file (a planned stage, or a
 * tester that has not generated examples) resolves to `[]`, not an error.
 */
const exampleFiles = import.meta.glob<{ default: unknown }>('../data/examples/*/*.json');

/** The raw catalog entries for one stage — what a route's `load` hands to the component. */
export async function loadExampleData(track: TrackId, stageNumber: number): Promise<unknown[] | null> {
	const loader = exampleFiles[`../data/examples/${track}/${stageNumber}.json`];
	if (!loader) return null;
	try {
		const mod = await loader();
		const list = mod?.default ?? mod;
		return Array.isArray(list) ? list : null;
	} catch {
		// A chunk that will not load is not worth breaking the stage page over.
		return null;
	}
}

export async function loadExamples(
	track: TrackId,
	stage: StageSpec | null | undefined
): Promise<ByteExample[]> {
	if (!stage) return [];
	const inline = inlineExamples(stage);
	if (inline.length) return inline;
	return normalizeByteExamples(await loadExampleData(track, stage.number));
}

/** How many examples a stage has, without loading any of them. */
export function byteExampleCount(stage: StageSpec | null | undefined): number {
	if (!stage) return 0;
	if (Array.isArray(stage.examples) && stage.examples.length) return inlineExamples(stage).length;
	return typeof stage.exampleCount === 'number' ? stage.exampleCount : 0;
}
